version: '3.8'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes: 
      - ./:/app  # this is a bind mount
      - /app/node_modules  # this is for anonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=deepanshu
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
      
    command: npm run dev
  mongo:
    environment: #mongo creds
      - MONGO_INITDB_ROOT_USERNAME=deepanshu 
      - MONGO_INITDB_ROOT_PASSWORD=mypassword