version: '3.8'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:   # for starting the mongo container before node, but this doesn't tell us that our database is up and running
      - mongo  # A case, that mongo container is up, but mongo's services are down
      # Mongoose will try to initiate the processes for 30 seconds, if not then our app will crash

  mongo:
    image: mongo
    environment: #mongo creds
      - MONGO_INITDB_ROOT_USERNAME=deepanshu 
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: #making anonymous volume into a human readable named volume
      - mongo-db:/data/db  # <name of volume>:<path on container>
  
  redis: 
    image: redis
    

# For the named volumes to be used for other services as well
volumes:
  mongo-db: