version: '3.8'
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    deploy:
      replicas: 8 # scale to 8 instances
      restart_policy:
        condition: any # restart if any instance fails
      update_config:
        parallelism: 2 # update 2 instances at a time
        delay: 15s # wait 15 seconds between updates
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js  

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
